name: HACS Action

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: read-all

jobs:
  hacs:
    name: HACS Action
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Harden GitHub Actions Runner
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
